it:
  adapter: postgresql
  encoding: unicode
  database: my_road_trip_it
  pool: 10
  username: postgres
  password: password
  host: postgres-0e4eb1a7
  port: 5432

development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: my_road_trip_development
  pool: 5
  username: postgres
  password: password
  host: postgres-0e4eb1a7
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: my_road_trip_test
  pool: 5
  username: postgres
  password: password
  host: postgres-0e4eb1a7
  port: 5432